language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

install:
  - composer selfupdate
  - travis_retry composer install --no-interaction

script: vendor/bin/phpunit --verbose --colors

before_script:
  - php artisan migrate:refresh --seed
  - mysql -e 'create database myapp_test;'
